const products=[{id:1,name:'Honey Cinnamon Latte',category:'coffee',description:'Espresso, steamed milk, honey and cinnamon.',price:5.5,icon:'☕',color:'#ead3b4',tag:'Fan favorite'},{id:2,name:'Citrus Cold Brew',category:'chilled',description:'Slow-steeped cold brew with orange zest.',price:5,icon:'🧊',color:'#d3e2d0',tag:'Refreshing'},{id:3,name:'Matcha Cloud',category:'tea',description:'Ceremonial matcha, vanilla and oat milk.',price:6,icon:'🍵',color:'#cbd9bd',tag:'New'},{id:4,name:'Almond Croissant',category:'coffee',description:'Flaky, buttery pastry with toasted almonds.',price:4.5,icon:'🥐',color:'#f0d08f',tag:''},{id:5,name:'Berry Hibiscus Fizz',category:'chilled',description:'Hibiscus tea, berries and sparkling water.',price:5.25,icon:'🍓',color:'#e9c5c0',tag:''},{id:6,name:'Vanilla Bean Cappuccino',category:'coffee',description:'Rich espresso, silky foam and vanilla.',price:5.75,icon:'☕',color:'#dfc2a2',tag:''},{id:7,name:'Ginger Peach Tea',category:'tea',description:'Bright black tea with peach and fresh ginger.',price:4.75,icon:'🍑',color:'#f1d0a5',tag:''},{id:8,name:'Iced Mocha',category:'chilled',description:'Chocolate, espresso and oat milk over ice.',price:5.5,icon:'🥤',color:'#d0b39d',tag:'Popular'}];
let cart=JSON.parse(localStorage.getItem('brewBloomCart')||'[]');const grid=document.querySelector('#product-grid');const cartDrawer=document.querySelector('#cart-drawer');const overlay=document.querySelector('#overlay');const money=n=>`$${n.toFixed(2)}`;
function renderProducts(filter='all'){grid.innerHTML=products.filter(p=>filter==='all'||p.category===filter).map(p=>`<article class="product-card"><div class="product-art" style="background:${p.color}"><span>${p.icon}</span>${p.tag?`<small>${p.tag}</small>`:''}</div><div class="product-info"><h3>${p.name}</h3><p>${p.description}</p><div class="product-bottom"><span class="price">${money(p.price)}</span><button class="add-button" data-add="${p.id}" aria-label="Add ${p.name} to cart">+</button></div></div></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(Number(b.dataset.add))));}
function addToCart(id){const item=cart.find(i=>i.id===id);item?item.qty++:cart.push({id,qty:1});saveCart();openCart();}
function saveCart(){localStorage.setItem('brewBloomCart',JSON.stringify(cart));renderCart();}
function renderCart(){const items=document.querySelector('#cart-items');const count=cart.reduce((s,i)=>s+i.qty,0);document.querySelector('#cart-count').textContent=count;const total=cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+p.price*i.qty},0);document.querySelector('#cart-total').textContent=money(total);if(!cart.length){items.innerHTML='<p class="empty-cart">Your cart is waiting for something delicious.</p>';return}items.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cart-item"><div class="cart-item-icon" style="background:${p.color}">${p.icon}</div><div><h4>${p.name}</h4><p>${money(p.price)} each</p><div class="qty-controls"><button data-dec="${p.id}" aria-label="Decrease quantity">−</button><strong>${i.qty}</strong><button data-inc="${p.id}" aria-label="Increase quantity">+</button></div></div><strong>${money(p.price*i.qty)}</strong></div>`}).join('');document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(Number(b.dataset.inc),1));document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(Number(b.dataset.dec),-1));}
function changeQty(id,change){const item=cart.find(i=>i.id===id);if(item){item.qty+=change;if(item.qty<=0)cart=cart.filter(i=>i.id!==id);saveCart();}}
function openCart(){cartDrawer.classList.add('open');overlay.classList.add('show');cartDrawer.setAttribute('aria-hidden','false')}function closeCart(){cartDrawer.classList.remove('open');overlay.classList.remove('show');cartDrawer.setAttribute('aria-hidden','true')}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');renderProducts(b.dataset.filter)});document.querySelector('#open-cart').onclick=openCart;document.querySelector('#close-cart').onclick=closeCart;overlay.onclick=closeCart;document.querySelector('.menu-toggle').onclick=e=>{const nav=document.querySelector('.nav-links');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))};document.querySelectorAll('.nav-links a').forEach(a=>a.onclick=()=>document.querySelector('.nav-links').classList.remove('open'));document.querySelector('#checkout-form').onsubmit=e=>{e.preventDefault();if(!cart.length){document.querySelector('#form-message').textContent='Add a drink before placing your order.';return}document.querySelector('#form-message').textContent='Order received! We will be in touch shortly ☕';cart=[];saveCart();e.target.reset()};document.querySelector('#year').textContent=new Date().getFullYear();renderProducts();renderCart();
